# Generated by Django 4.2.23 on 2025-06-29 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalClaim',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under-review', 'Under Review'), ('pending-approval', 'Pending Approval'), ('approved', 'Approved'), ('in-processing', 'In Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('beneficiary_nom', models.CharField(max_length=100)),
                ('beneficiary_prenom', models.CharField(max_length=100)),
                ('beneficiary_date_naissance', models.DateField()),
                ('beneficiary_cin', models.CharField(max_length=20)),
                ('beneficiary_sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('lien_parente', models.CharField(choices=[('conjoint', 'Conjoint'), ('enfant', 'Enfant')], max_length=20)),
                ('montant_frais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_soins', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cnss_reference', models.CharField(blank=True, max_length=50)),
                ('processing_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('radiology', 'Radiology'), ('laboratory', 'Laboratory')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='claims.medicalclaim')),
            ],
            options={
                'unique_together': {('claim', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.medicalclaim')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claimsection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
